# Generated by Django 5.0.14 on 2026-08-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('perfume_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfume_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='perfumes/')),
                ('concentration', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('Parfum', 'Parfum'), ('EDC', 'Eau de Cologne')], default='EDT', max_length=20)),
                ('size', models.CharField(choices=[('decant', 'Decant'), ('full_size', 'Full Size')], default='full_size', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('none', 'None')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_start', models.DateTimeField(blank=True, null=True)),
                ('discount_end', models.DateTimeField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('limited_quantity', models.IntegerField(blank=True, null=True)),
                ('limited_sold', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('offer_description', models.TextField(blank=True)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order'), ('discontinued', 'Discontinued')], default='in_stock', max_length=20)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('pre_order_date', models.DateTimeField(blank=True, null=True)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('reorder_level', models.IntegerField(default=5)),
                ('warehouse', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='catalog.brand')),
            ],
            options={
                'db_table': 'perfume',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('product_type', models.CharField(choices=[('decant', 'Decant'), ('full_size', 'Full Size'), ('sample', 'Sample')], default='full_size', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.perfume')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.perfume')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=models.Index(fields=['brand'], name='perfume_brand_i_74c87d_idx'),
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=models.Index(fields=['is_featured'], name='perfume_is_feat_24d254_idx'),
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=models.Index(fields=['stock_status'], name='perfume_stock_s_7199e7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['perfume'], name='product_perfume_da84f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_is_acti_916801_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('perfume', 'product_type')},
        ),
    ]
