# Generated by Django 5.0.14 on 2026-08-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_order_snapshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordershippingsnapshot',
            options={'ordering': ['snapshot_id']},
        ),
    ]
