# Generated by Django 5.0.14 on 2026-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('table_affected', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=150, unique=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BulkBottle',
            fields=[
                ('bottle_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('bottle_size_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ml_remaining', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('authenticity_verified', models.IntegerField()),
                ('verification_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bulk_bottle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'chatbot_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecantBatch',
            fields=[
                ('decant_batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_created', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decant_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_used', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('was_successful', models.IntegerField()),
                ('attempted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'login_attempt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'password_reset_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('perfume_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfume_name', models.CharField(max_length=200)),
                ('concentration', models.CharField(max_length=7)),
                ('top_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('base_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('longevity_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sillage', models.CharField(blank=True, max_length=8, null=True)),
                ('recommended_season', models.CharField(blank=True, max_length=10, null=True)),
                ('target_gender', models.CharField(max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=11)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_verified_purchase', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
